services:
  postgres:
    image: postgres
    container_name: mypostgres
    ports:
      - 5433:5432
    networks:
      - mynetwork
    env_file:
      - .env
    volumes:
      - myvolume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d mydatabase -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: mybackend
    container_name: mybackend
    build: .
    ports:
      - 3000:3000
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

networks:
  mynetwork:
    name: mynetwork

volumes:
  myvolume: