services:
  postgres:
    image: postgres
    container_name: mypostgres
    ports:
      - 5433:5432
    networks:
      - mynetwork
    env_file:
      - .env.test
    volumes:
      - myvolume:/var/lib/postgresql/data

  backend:
    image: mybackend
    container_name: mybackend
    build: .
    ports:
      - 3000:3000
    networks:
      - mynetwork
    depends_on:
      - postgres
    env_file:
      - .env.test

networks:
  mynetwork:
    name: mynetwork

volumes:
  myvolume: